services:
  app:
    build:
      context: ./vite-project # The build context, where the Dockerfile is located
      dockerfile: Dockerfile.dev # The Dockerfile to use for building the image
    container_name: sample-app-dev # The name of the container
    restart: always # Always restart the container if it stops
    ports:
      - 3000:3000 # Map port 3000 on the host to port 3000 on the container
    volumes:
      - ./vite-project:/vite-project # Mount the ./app directory on the host to /app in the container
      - /vite-project/node_modules # Anonymous volume to persist node_modules
    networks:
      - network # Connect the container to the 'network' network

networks:
  network:
    driver: bridge # Use the bridge network driver
