# Use the official .NET SDK image as a build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["asp-net-core-project.csproj", "."]
RUN dotnet restore "./asp-net-core-project.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "asp-net-core-project.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "asp-net-core-project.csproj" -c Debug -o /app/publish

# Use the official ASP.NET Core runtime image
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS final
WORKDIR /app

# Related to running the migrations on start up
COPY --from=build /src /src
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY --from=publish /app/publish .
EXPOSE 4000
ENTRYPOINT ["sh", "-c", "dotnet ef database update --project /src/asp-net-core-project.csproj && dotnet asp-net-core-project.dll"]
